/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpipe.h"
#include "protocol.h"

void
rpipe_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;

	char str[] = "Hello World! ;P";
	struct packet_t pck;
	pck.fid = 1;
	pck.msg_data = str;
	pck.mgs_size = sizeof(str);

	char *msg = packet2str(pck);

	char * open_1_arg = msg;
	int  *result_2;
	int  close_1_arg;
	char * *result_3;
	int  recv_1_arg;
	int  *result_4;
	char * send_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, rpipe, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = open_1(&open_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
//	result_2 = close_1(&close_1_arg, clnt);
//	if (result_2 == (int *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_3 = recv_1(&recv_1_arg, clnt);
//	if (result_3 == (char **) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_4 = send_1(&send_1_arg, clnt);
//	if (result_4 == (int *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpipe_1 (host);
exit (0);
}
