/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPIPE_H_RPCGEN
#define _RPIPE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define rpipe 0x20100160
#define v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define open 1
extern  int * open_1(char **, CLIENT *);
extern  int * open_1_svc(char **, struct svc_req *);
#define close 2
extern  int * close_1(int *, CLIENT *);
extern  int * close_1_svc(int *, struct svc_req *);
#define recv 3
extern  char ** recv_1(int *, CLIENT *);
extern  char ** recv_1_svc(int *, struct svc_req *);
#define send 4
extern  int * send_1(char **, CLIENT *);
extern  int * send_1_svc(char **, struct svc_req *);
extern int rpipe_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define open 1
extern  int * open_1();
extern  int * open_1_svc();
#define close 2
extern  int * close_1();
extern  int * close_1_svc();
#define recv 3
extern  char ** recv_1();
extern  char ** recv_1_svc();
#define send 4
extern  int * send_1();
extern  int * send_1_svc();
extern int rpipe_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPIPE_H_RPCGEN */
