/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rcb.h"


void
rcb_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int rcallback_1_fid;
	int rcallback_1_cbtype;
	int rcallback_1_retval;
	char *rcallback_1_msg;

#ifndef	DEBUG
	clnt = clnt_create (host, rcb, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = rcallback_1(rcallback_1_fid, rcallback_1_cbtype, rcallback_1_retval, rcallback_1_msg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rcb_1 (host);
exit (0);
}
