/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpipe.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpipe_open_1(char *name, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpipe_open,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &name,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpipe_close_1(int fid, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpipe_close,
		(xdrproc_t) xdr_int, (caddr_t) &fid,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpipe_recv_1(int fid, u_int max_len, char **clnt_res,  CLIENT *clnt)
{
	rpipe_recv_1_argument arg;
	arg.fid = fid;
	arg.max_len = max_len;
	return (clnt_call (clnt, rpipe_recv, (xdrproc_t) xdr_rpipe_recv_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpipe_send_1(int fid, char *msg, int *clnt_res,  CLIENT *clnt)
{
	rpipe_send_1_argument arg;
	arg.fid = fid;
	arg.msg = msg;
	return (clnt_call (clnt, rpipe_send, (xdrproc_t) xdr_rpipe_send_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
