/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpipe.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_rpipe_open_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (rpipe_open_1_svc(*argp, result, rqstp));
}

int
_rpipe_close_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (rpipe_close_1_svc(*argp, result, rqstp));
}

int
_rpipe_recv_1 (rpipe_recv_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpipe_recv_1_svc(argp->fid, argp->max_len, result, rqstp));
}

int
_rpipe_send_1 (rpipe_send_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (rpipe_send_1_svc(argp->fid, argp->msg, result, rqstp));
}

static void
rpipe_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *rpipe_open_1_arg;
		int rpipe_close_1_arg;
		rpipe_recv_1_argument rpipe_recv_1_arg;
		rpipe_send_1_argument rpipe_send_1_arg;
	} argument;
	union {
		int rpipe_open_1_res;
		int rpipe_close_1_res;
		char *rpipe_recv_1_res;
		int rpipe_send_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpipe_open:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpipe_open_1;
		break;

	case rpipe_close:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpipe_close_1;
		break;

	case rpipe_recv:
		_xdr_argument = (xdrproc_t) xdr_rpipe_recv_1_argument;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpipe_recv_1;
		break;

	case rpipe_send:
		_xdr_argument = (xdrproc_t) xdr_rpipe_send_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_rpipe_send_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rpipe_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (rpipe, v1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, rpipe, v1, rpipe_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (rpipe, v1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, rpipe, v1, rpipe_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (rpipe, v1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
