/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPIPE_H_RPCGEN
#define _RPIPE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct rpipe_recv_1_argument {
	int fid;
	u_int max_len;
};
typedef struct rpipe_recv_1_argument rpipe_recv_1_argument;

struct rpipe_send_1_argument {
	int fid;
	char *msg;
};
typedef struct rpipe_send_1_argument rpipe_send_1_argument;

#define rpipe 0x20100160
#define v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpipe_open 1
extern  enum clnt_stat rpipe_open_1(char *, int *, CLIENT *);
extern  bool_t rpipe_open_1_svc(char *, int *, struct svc_req *);
#define rpipe_close 2
extern  enum clnt_stat rpipe_close_1(int , int *, CLIENT *);
extern  bool_t rpipe_close_1_svc(int , int *, struct svc_req *);
#define rpipe_recv 3
extern  enum clnt_stat rpipe_recv_1(int , u_int , char **, CLIENT *);
extern  bool_t rpipe_recv_1_svc(int , u_int , char **, struct svc_req *);
#define rpipe_send 4
extern  enum clnt_stat rpipe_send_1(int , char *, int *, CLIENT *);
extern  bool_t rpipe_send_1_svc(int , char *, int *, struct svc_req *);
extern int rpipe_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpipe_open 1
extern  enum clnt_stat rpipe_open_1();
extern  bool_t rpipe_open_1_svc();
#define rpipe_close 2
extern  enum clnt_stat rpipe_close_1();
extern  bool_t rpipe_close_1_svc();
#define rpipe_recv 3
extern  enum clnt_stat rpipe_recv_1();
extern  bool_t rpipe_recv_1_svc();
#define rpipe_send 4
extern  enum clnt_stat rpipe_send_1();
extern  bool_t rpipe_send_1_svc();
extern int rpipe_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpipe_recv_1_argument (XDR *, rpipe_recv_1_argument*);
extern  bool_t xdr_rpipe_send_1_argument (XDR *, rpipe_send_1_argument*);

#else /* K&R C */
extern bool_t xdr_rpipe_recv_1_argument ();
extern bool_t xdr_rpipe_send_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPIPE_H_RPCGEN */
