/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpipe.h"

bool_t
xdr_rpipe_recv_1_argument (XDR *xdrs, rpipe_recv_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->max_len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpipe_send_1_argument (XDR *xdrs, rpipe_send_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fid))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->msg, ~0))
		 return FALSE;
	return TRUE;
}
