/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpipe.h"


void
rpipe_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *rpipe_open_1_name;
	enum clnt_stat retval_2;
	int result_2;
	int rpipe_close_1_fid;
	enum clnt_stat retval_3;
	char *result_3;
	int rpipe_recv_1_fid;
	u_int  rpipe_recv_1_max_len;
	enum clnt_stat retval_4;
	int result_4;
	int rpipe_send_1_fid;
	char *rpipe_send_1_msg;

#ifndef	DEBUG
	clnt = clnt_create (host, rpipe, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = rpipe_open_1(rpipe_open_1_name, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = rpipe_close_1(rpipe_close_1_fid, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = rpipe_recv_1(rpipe_recv_1_fid, rpipe_recv_1_max_len, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = rpipe_send_1(rpipe_send_1_fid, rpipe_send_1_msg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpipe_1 (host);
exit (0);
}
